apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - hpa.yaml
  - service.yaml

configMapGenerator:
  - name: chat

images:
  - name: ripard/chat-app
    newTag: latest
